name: Hello World Workflow

# Trigger the workflow on push to any branch
on: 
  push:
    branches:
      - '*'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Hello world step
      - name: Print Hello World
        run: echo "Hello, World!"
